### ISSUE TITLE
Numbers not in circles after 13 star button presses

### ISSUE THREAD

**Issue by DipanshKhandelwal** [sugarlabs/connect-the-dots-activity#16]
Activity showing unexpected behavior.
![conn-un](https://user-images.githubusercontent.com/24923974/34325298-ce025e14-e8b3-11e7-88a0-e9d4db9fbd3a.png)

Steps to reproduce:
1) Click the **Star** button 13 times.

**Comment by quozl** [comment]
Several behaviours in your screen capture could be unexpected to you; but I've no idea if they are unexpected to the authors or others.  Could you list the unexpected behaviours please?  Otherwise someone could work on one of the unexpected behaviours and not solve your problem.

**Comment by DipanshKhandelwal** [comment]
**Actual Behaviour:**
The numbers should be shown inside those circles.
![1](https://user-images.githubusercontent.com/24923974/34364432-1bc28774-eaac-11e7-8972-64ceb2cc2bee.png)
![2](https://user-images.githubusercontent.com/24923974/34364434-1ed601d4-eaac-11e7-8456-558145b160a2.png)

**Comment by quozl** [comment]
I've fixed your issue title; your used vague wording.  Please be more precise in future.

Did a previous version not have this problem?  If so, I suggest you do a `git bisect` to isolate which commit caused it.

**Comment by DipanshKhandelwal** [comment]
@quozl check #17 once.
