### ISSUE TITLE
Need to add navbar option on the top  as well as the UI needs to get improve 

### ISSUE THREAD

**Issue by Bhumika-00** [sugarlabs/connect-the-dots-activity#27]
Description:

This PR introduces a top navigation bar (navbar) with a new Marker Color Choice feature and enhances the user interface (UI) to make it more child-friendly. The objective is to provide an engaging and accessible experience for younger users while offering customization options for a more personalized experience.

Changes:
Top Navbar:

Marker Color Choice:
A new dropdown in the navbar allows users to select a "marker color" for their interactions (e.g., highlighting text, selecting items, etc.). This feature offers a fun way for kids to personalize their experience by choosing their preferred colors.
The available color options include a variety of playful colors (e.g., red, blue, yellow, green, etc.), ensuring that kids can express themselves while using the platform.
The selected marker color is applied globally across the platform wherever interaction with text or objects occurs (such as when kids select or highlight items).

UI Enhancements for Kids:

Color Scheme: A bright and playful color scheme with pastel tones and colorful accents that appeal to children.
Typography: Child-friendly fonts with larger sizes for readability and legibility.
Icons and Buttons: Large, easy-to-tap buttons with rounded edges and clear, simple icons for intuitive navigation.
Animations: Fun animations are added for buttons, transitions, and hover effects to keep the interface engaging but not overwhelming.
Simplified Layout: The interface is designed to reduce visual clutter, focusing on important features and easy access.
Interactive Elements: Engaging features like fun sounds or simple animations enhance the user experience for children.

**Comment by quozl** [comment]
Not an issue, closing.
